Repository krayong/Study_Partner, pull requests merged in 2021-03, with the labels that each got.

#38 update contributing.md
  CONTRIBUTING.md
Labels: GSSOC21, Level1, documentation

#43 added app-logo in login and register activity
  app/src/main/res/layout/activity_create_account.xml
  app/src/main/res/layout/activity_login.xml
Labels: GSSOC21, Level2, enhancement

#45 Same notebook Image resource update in OnBoarding Activity with better resolution and also check it on device..
  app/src/main/java/com/studypartner/activities/OnBoardingActivity.java
  app/src/main/res/drawable-hdpi/on_boarding_notebook_image.png
  app/src/main/res/drawable-ldpi/on_boarding_notebook_image.png
  app/src/main/res/drawable-mdpi/on_boarding_notebook_image.png
  app/src/main/res/drawable-xhdpi/on_boarding_notebook_image.png
  app/src/main/res/drawable-xxhdpi/on_boarding_notebook_image.png
  app/src/main/res/drawable-xxxhdpi/on_boarding_notebook_image.png
Labels: GSSOC21, Level2, enhancement

#50 Added Tech stack
  README.md
Labels: GSSOC21, Level0, documentation, good first issue

#58 Images moved to Screenshot folder
  README.md
  screenshots/Attendance Screen.jpg
  screenshots/File Screen.jpg
  screenshots/Home Screen.jpg
  screenshots/Reminder Screen.jpg
  screenshots/Star Screen.jpg
  screenshots/feature-graphic.png
Labels: GSSOC21, Level0, documentation, good first issue

#59 Added hint for EditText in notes fragment for entering folder name
  app/src/main/java/com/studypartner/fragments/NotesFragment.java
Labels: GSSOC21, Level2, enhancement, good first issue

#65 Create auto-author-assign.yml
  .github/workflows/auto-author-assign.yml
Labels: GSSOC21, Level1, enhancement

#70 Updated readme file to add contributors section
  README.md
Labels: GSSOC21, Level0, documentation, good first issue

#66 Create auto-issue-assign.yml
  .github/workflows/auto-issue-assign.yml
Labels: GSSOC21, Level2

#72 Change TextInputEditText cursor color
  app/src/main/res/drawable/color_cursor.xml
  app/src/main/res/layout/activity_create_account.xml
  app/src/main/res/layout/activity_login.xml
  app/src/main/res/layout/attendance_item_subject_name_dialog.xml
  app/src/main/res/layout/fragment_profile.xml
  app/src/main/res/layout/fragment_reminder_dialog.xml
  app/src/main/res/layout/notes_add_link_layout.xml
  app/src/main/res/layout/notes_add_note_layout.xml
Labels: GSSOC21, Level2, bug

#74 Patch auto issue assign
  .github/workflows/auto-issue-assign.yml
Labels: GSSOC21, Level0, bug

#75 Change default AlertDialog to custom app theme AlertDialog
  app/src/main/java/com/studypartner/fragments/AttendanceFragment.java
  app/src/main/java/com/studypartner/fragments/FileFragment.java
  app/src/main/java/com/studypartner/fragments/NotesFragment.java
  app/src/main/java/com/studypartner/fragments/ProfileFragment.java
  app/src/main/java/com/studypartner/fragments/ReminderFragment.java
  app/src/main/java/com/studypartner/fragments/StarredFragment.java
  app/src/main/res/layout/alert_dialog_box.xml
Labels: GSSOC21, Level3

#68 Updated the welcome message.
  .github/config.yml
Labels: GSSOC21, Level0, documentation, good first issue

#69 Updated readme file for adding badges
  README.md
Labels: GSSOC21, Level1, documentation, good first issue

#79 Added Styled Toast
  app/build.gradle
  app/src/main/java/com/studypartner/activities/CreateAccountActivity.java
  app/src/main/java/com/studypartner/activities/LoginActivity.java
  app/src/main/java/com/studypartner/activities/MainActivity.java
  app/src/main/java/com/studypartner/fragments/AttendanceFragment.java
  app/src/main/java/com/studypartner/fragments/FileFragment.java
  app/src/main/java/com/studypartner/fragments/NotesFragment.java
  app/src/main/java/com/studypartner/fragments/ProfileFragment.java
  app/src/main/java/com/studypartner/fragments/ReminderDialogFragment.java
  app/src/main/java/com/studypartner/fragments/StarredFragment.java
  app/src/main/java/com/studypartner/utils/Connection.java
  app/src/main/java/com/studypartner/utils/FileUtils.java
  app/src/main/res/values/styles.xml
Labels: GSSOC21, Level3, enhancement

#81 Fixed SIGN IN WITH GOOGLE failed state
  app/src/main/java/com/studypartner/activities/LoginActivity.java
Labels: GSSOC21, Level2, bug

#77 Updated the issues template.
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: GSSOC21, Level0, documentation, good first issue

#84 Added UNDO option after delete action
  app/src/main/java/com/studypartner/fragments/FileFragment.java
  app/src/main/java/com/studypartner/fragments/NotesFragment.java
  app/src/main/java/com/studypartner/fragments/StarredFragment.java
  app/src/main/java/com/studypartner/models/FileItem.java
  app/src/main/res/layout/notes_item.xml
  app/src/main/res/values/strings.xml
Labels: GSSOC21, Level3, enhancement

#88 added playstore icon
  README.md
Labels: GSSOC21, Level0, documentation, good first issue
